- name: variables
  hosts: localhost
  vars: #variable declaration
    courses: "Ansible"
    Trainer: "Naresh"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hii, we are Learning {{courses}} from Trainer {{Trainer}},Duration is {{Duration}}."