- name: variables from files
  hosts: web
  vars_prompt:
  - name: USERNAME
    prompt: pls enter your username
    private: false

  - name: PASSWORD
   prompt: pls enter your password
   private: true
 tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hi, username: {{USERNAME}},password is {{PASSWORD}}."