- name: datatypes 
  hosts: web
  vars:
   course: Devops with Aws
    
   Tools:
   - Ansible
   - chef
   - puppet
   - scripting

   Experience:
    Linux: 3
    Aws : 4
    Devops: 1

   Real time project: true

  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Iam Learning: {{course}}, Tools covered: {{Tools}}, Experience is: {{Experience}} and Realtime project is: Realtimeproject is:{{Realtimeproject}}"




   
   


