- name: conditions
  hosts: web
  tasks:
  - name: check usrr exists or not
    ansible.builtin.command: id expense
    register: USER
    ignor_errors: true

  - name: print information
    ansible.builtin.debug:
      msg: "Hello info: {{USER}}"

  - name: create user
    ansible.buitin.command: useradd expense
    When: USER,rc != 0
  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"
