- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Iam learning {{git | default('Myself') }}" 


- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"


- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
    msg: "{{ greeting | lower }}"








