- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Iam learning {{git | default('Myself') }}" 


- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: print min amd max age
  hosts: localhost
  vars:
    ages: [20,30,45,60]
  tasks:
  - name: print min and max age
    ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,2,2,3,3,4,4,5,5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

- name: converting dictionary in to items/list
  hosts: web
  vars:
    my_dict: 
    couse: Devops
    Trainer: shiva
    Duration: 120  hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
    msg: "before convert: {{my_dict}}"
  
 







