- name: configure Database mysql server
  hosts: db
  become: yes
  vars:
    log_hosts: db.172.31.18.216
  vars_prompt:
  - name: mysql_root_password
    prompt: pls enter root password
    private: yes

  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: MySQl-server
      state: latest

  - name: strat and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started

  - name: installing python dependencies in mysql server
    ansible.builtin.pip:
      name: 
      - pyMySQL
      - cryptography
    executable: python 3.9
    
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{login_host}}"
      ignore_errors: yes
      register: "{{ mysql_connection_output }}"

  - name: print information
    ansible.builtin.debug:
      msg: "{{ mysql_connection_output }}"
    


  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition


